Make GitHub Discussions link point to GitHub Community and remove other support options
atom-community/atom pull request #422
Opened 2022-07-03 18:51 UTC by softorangetech11

### Requirements for Contributing Documentation

* Fill out the template below. Any pull request that does not include enough information to be reviewed in a timely manner may be closed at the maintainers' discretion.
* The pull request must only contribute documentation (for example, markdown files or API docs). To contribute other changes, you must use a different template. You can see all templates at <https://github.com/atom/.github/tree/master/.github/PULL_REQUEST_TEMPLATE>.

### Description of the Change
Add the GitHub Discussions link for Atom-Community rather than Atom's repository

### Release Notes
N/A

2022-07-03 19:38 UTC, DeeDeeG commented
I don't know how others feel about this, but the Flight Manual has a ton of useful info in it, and I believe it's not that hard to get our fork of it going. Just have to disable link 404 and 304 checks, and it should post a build. So eventually we want to keep pointing people to the flight manual, just our copy that we can keep updated.

2022-07-03 21:46 UTC, aminya requested changes
Those links include the information that is not covered in the discussion link.

2022-07-04 01:12 UTC, softorangetech11 reviewed
It's gonna be there

2022-07-04 01:12 UTC, softorangetech11 commented on SUPPORT.md
> -* User Documentation &mdash; [The Atom Flight Manual](https://flight-manual.atom.io)
I'll add the flight manual

2022-07-04 01:17 UTC, aminya requested changes

2022-07-04 01:17 UTC, aminya commented on SUPPORT.md
> +If you're looking for support for Atom Community you can go to our message board or Atom branded Flight manual linked below:
```suggestion
If you're looking for support for Atom Community, you can go to our message board or the Flight manual linked below:
```

2022-07-04 01:20 UTC, aminya approved these changes

2022-07-04 01:20 UTC, merged