SUPPORT.md add developer documentation, and a minor update
atom-community/atom pull request #430
Opened 2022-07-05 00:13 UTC by softorangetech11

### Requirements for Contributing Documentation

* Fill out the template below. Any pull request that does not include enough information to be reviewed in a timely manner may be closed at the maintainers' discretion.
* The pull request must only contribute documentation (for example, markdown files or API docs). To contribute other changes, you must use a different template. You can see all templates at <https://github.com/atom/.github/tree/master/.github/PULL_REQUEST_TEMPLATE>.

### Description of the Change
A simple update to the SUPPORT.md file that rebrands almost everything and one minor update.

### Release Notes
Not applicable

2022-07-05 00:46 UTC, aminya requested changes

2022-07-05 00:46 UTC, aminya commented on SUPPORT.md
> +If you're looking for support for Atom Community there are a lot of options, check out:
```suggestion
If you're looking for support for Atom Community, there are a lot of options to check out:
```

2022-07-05 00:47 UTC, aminya commented on SUPPORT.md
> +If you're looking for support for Atom Community there are a lot of options, check out:
Please include `[skip ci]` in the commit message

2022-07-05 00:52 UTC, softorangetech11 reviewed
that's good

2022-07-06 02:03 UTC, aminya approved these changes

2022-07-06 02:03 UTC, merged